446/kobo empty geofield error
WFP-VAM/prism-frontend pull request #448
Opened 2022-04-11 08:58 UTC by tdlinh2712

This quick fix resolves #446.

The error is because when kobo form return an empty lat/lon value and when the `gemo_field_type` is empty, the `parse_form_response` function cannot map the result into a dictionary of latitude and longitude points

This is a temporary fix, but looks like the process of parsing json data from kobo form at the moment is very complex/varies case by case. @ericboucher @wadhwamatic, do you have any idea how we can make it a bit more generalized? 

How to test:
1. run the API locally
2. Update kh_incident_report in `config\cambodia\layers.json` with:
```"form_name": "ទម្រង់ ឧបទ្ទវហេតុ"
or
"form_name": "NCDM_Live_Form"```
3. Change `data` and `date_url` into:
```"data": "http://localhost/kobo/forms",
    "date_url": "http://localhost/kobo/forms",
```
3. Run PRISM app with REACT_APP_COUNTRY='cambodia'

2022-04-11 16:19 UTC, ericboucher commented
@tdlinh2712 Thanks for the quick turnaround! It seems to work well for me.

@wadhwamatic the main reason was that these fields don't have location info available.

2022-04-11 16:19 UTC, ericboucher commented
@tdlinh2712 I made a few changes to make it more future proof and accept "location" type data as [lat, lon] instead of a geopoint string

2022-04-11 16:20 UTC, ericboucher approved these changes

2022-04-11 21:57 UTC, wadhwamatic commented
Thanks @ericboucher and @tdlinh2712 for the quick action. I no longer see the error, but see a few issues:
1. API generates a warning repeatedly 'api_1  | WARNING:app.kobo:geopoint [None, None] coud not be parsed to {lat,lon}'. I see it's just a warning and Linh already mentioned the implementation is temporary, but I'd like to know if we can address this in the near term. 
2. I don't know if this is related to the point above, but I see the load time for this query is long, 12-13 seconds. http://localhost/kobo/forms?beginDateTime=2022-04-11&endDateTime=2022-04-11&formName=%E1%9E%91%E1%9E%98%E1%9F%92%E1%9E%9A%E1%9E%84%E1%9F%8B%20%E1%9E%A7%E1%9E%94%E1%9E%91%E1%9F%92%E1%9E%91%E1%9E%9C%E1%9E%A0%E1%9F%81%E1%9E%8F%E1%9E%BB&datetimeField=Date_report&geomField=location&measureField=NumPeoAff&koboUrl=https://kobo.humanitarianresponse.info/api/v2/assets.json
3. I no longer see the measurement field in the response, which then gives incorrect values in the map and tooltip. We should be getting 'NumPeoAff' back and using that for the map symbology and tooltip.
<img width="1440" alt="Screen Shot 2022-04-11 at 14 56 04" src="https://user-images.githubusercontent.com/3343536/162840097-abf16ddd-b539-42e2-a19e-0b27f3512510.png">

2022-04-11 21:58 UTC, wadhwamatic requested changes
See my comments on the PR

2022-04-11 22:52 UTC, ericboucher commented
@wadhwamatic

1. I can remove the warning or log it as debug or info instead. It does warn us that location info is missing
2. The slowness likely comes from the kobo API but I will add a task to add timers on our end to be sure
3. The data returned doesn't seem to have the field you are looking for. Here is what it looks like:

`
[{'_id': 277929637, 'formhub/uuid': '7776ff25899d4137898a2f73cb2e2d4c', 'start': '2022-04-10T11:10:16.434-07:00', 'end': '2022-04-10T11:10:44.745-07:00', 'G1/q_Enum': 'test', 'G1/Date_report': '2022-04-10', 'G2/Date_Dis': '2022-04-08', 'G2/DisTyp': '4', 'G2/Province': '01', 'G2/District': '0103', 'G2/Commune': '010302', 'group_tc1fy38/group_pf1pd97/NumVillAff': '2500', '__version__': 'vTW2Tp4MyTeyw5ozr2e4Qk', '_version_': 'vv5yNUomTiEwpiEUADRJt8', '_version__001': 'viD2ksZ6r3ecnuWLvDhSW3', '_version__002': 'vrsQRgZ3mfbfN39Aqu5Drv', '_version__003': 'vqhAgCKXkSHt9sZPHvE6Uu', '_version__004': 'vsqUhoEj2yV6QBSLVoNPgP', '_version__005': 'vecVBRVEHBNjEFtvmTmSGv', '_version__006': 'vDC2x3f7cxVfk6qA4xkrj2', '_version__007': 'vzP7FpMtuUguJvBSCsUWyK', '_version__008': 'vE6MJM6CN74B2ibL7aRVqY', 'meta/instanceID': 'uuid:5bae99b9-234f-4c8a-9f56-aa9b7baa6229', '_xform_id_string': 'abzPNBbJD3T9RNV6pm4WFb', '_uuid': '5bae99b9-234f-4c8a-9f56-aa9b7baa6229', '_attachments': [], '_status': 'submitted_via_web', '_geolocation': [None, None], '_submission_time': '2022-04-10T18:10:46', '_tags': [], '_notes': [], '_validation_status': {}, '_submitted_by': None}]
`

2022-04-12 00:59 UTC, wadhwamatic commented
@ericboucher

ok, thanks. For your 3rd point though, the field 'NumPeoAff' exists. It may not always have data, but in those cases, we should treat no value as a 0. I'm testing with form name 'ទម្រង់ ឧបទ្ទវហេតុ' and I see dates where there are values, but they still don't show values in PRISM. I also tested with 'NumVillAff' and have the same issue

<img width="506" alt="Screen Shot 2022-04-11 at 17 48 01" src="https://user-images.githubusercontent.com/3343536/162857080-a0ede4fc-b423-4cb3-9c65-cecdee446729.png">

2022-04-12 04:26 UTC, wadhwamatic commented
Thanks @ericboucher for that last fix. Results are coming in as expected now.

2022-04-12 04:26 UTC, wadhwamatic approved these changes

2022-04-13 06:40 UTC, tdlinh2712 reviewed
looks good to me!

2022-04-13 17:35 UTC, merged