Add auto linter for json files
WFP-VAM/prism-frontend pull request #527
Opened 2022-07-18 11:42 UTC by PysarenkoDS-BWT

2022-07-18 19:25 UTC, ericboucher commented
When/how do we run it? I'm surprised it doesn't change anything in the existing JSON files

2022-07-25 08:26 UTC, PysarenkoDS-BWT commented
Add script to run prettier for JSON files, run only manually (not add automatically), because this not fast operation

2022-07-25 09:00 UTC, ericboucher commented
@PysarenkoDS-BWT thanks for updating the files. Please make sure that the CI tests are failing when the files are not properly formated

2022-07-25 12:39 UTC, PysarenkoDS-BWT commented
@ericboucher I think we can't check it in CI/CD because for this check need a loot of memory, remove this check?

2022-07-26 09:06 UTC, ericboucher requested changes
@PysarenkoDS-BWT actually, let's not run this on files that are in public/data/COUNTRY_NAME but only on config files for now. This is making all the geojson files even bigger, which is clearly not what we want, thanks :)

2022-07-26 10:16 UTC, ericboucher commented on src/components/MapView/AlertForm/index.tsx
> +  const onOptionChange =
Why are the ts and tsx files changing? Can we limit the changes to  json files?

2022-07-26 12:32 UTC, ericboucher approved these changes

2022-07-26 12:32 UTC, merged